export const demographics = [
  "Women 18–24",
  "Men 18–24",
  "Women 25–34",
  "Men 25–34",
  "Women 35–44",
  "Men 35–44",
  "Women 45+",
  "Men 45+",
  "Teens",
  "Kids",
  // "High-Income / Affluent",
  // "Budget-Conscious Shoppers",
  // "Health & Wellness Focused",
  // "Trend & Style Seekers",
  // "Family-Oriented",
  // "Homeowners / New Home Buyers",
  // "Tech-Savvy Consumers",
];
